[package]
name = "frenezulo"
version = "0.1.0"
edition = "2021"

[dependencies]
bytes = "1.2.1"
generic_error = "0.2.0"
lunatic = "0.11.1"
multimap = "0.8.3"
serde = "1.0.144"
serde_bytes = "0.11.7"
submillisecond = "0.2.0-alpha0"
